# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5af845293de3f87172a3109f607e8fb0acdcb400e033766db6cfa43c6955b7bd813b7e8c067d974ebfa9df2b3d253a3e0d51b076fcf99a98047d3e288d2d270d

test:
  secret_key_base: 20996e7c2188e6963b95aee81a76d456f1667cb0b174084bdf2a248e930ebf87cc3c62ca9ec14de152e12ffaa64ce9937a9f3a02d17eff87050767a56d7b34ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
